server:
  port: 8081
---
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecobook_user
    username: ecobook
    password: 123456
---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka